---
- name: Common tasks FTW
  hosts: all
  sudo: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base big service
  hosts: big
  sudo: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: big, tags: big }

  # Install forever - A simple CLI tool for ensuring that a given node script runs continuously
  tasks:
  - name: "Install forever (to run Node.js app)."
    npm: name=forever global=yes state=present

  - name: create symlink for forever to work with nodejs
    shell: if [ ! -L /usr/bin/node ]; then sudo ln -s /usr/bin/nodejs /usr/bin/node; fi

  - name: "Check list of Node.js apps running."
    command: forever list
    register: forever_list
    changed_when: false

  - name: "Start Big service."
    command: forever start /tmp/big-service/big-service.js
    when: "forever_list.stdout.find('/tmp/big-service/big-service.js') == -1"

  - name: "Restart Big service if it was redeployed"
    command: forever restart /tmp/big-service/big-service.js
    when: ("forever_list.stdout.find('/tmp/big-service/big-service.js') == -1") and
          (bigcontent.changed)
